version: "3.8"

services:
  backend:
    build: ./
    ports:
      - 5000:5000
  # web:
  #   image: nginx
  #   ports:
  #     - 8080:80
  db:
    image: redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes